### ISSUE TITLE
xunit: define codefixes for StringAsserts

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions.analyzers#145]
The asserts defined in https://github.com/xunit/assert.xunit/blob/main/StringAsserts.cs

- [x] `Contains(string expectedSubstring, string actualString)` #221 
- [x] `DoesNotContain(string expectedSubstring, string actualString)` #223 
- [x] `DoesNotMatch(string expectedRegexPattern, string actualString)` #225
- [x] `DoesNotMatch(Regex expectedRegex, string actualString)` #225
- [x] `Matches(string expectedRegexPattern, string actualString)` #224
- [x] `Matches(Regex expectedRegex, string actualString)` #224
- [x] `Empty(string value)` #226
- [x] `EndsWith(string expectedEndString, string actualString)` #227
- [x] `StartsWith(string expectedStartString, string actualString)` #228
- [x]  `Equal(string expected, string actual)` #229

**Comment by Meir017** [comment]
@jnyrup / @dennisdoomen any idea about an equivalent for using `StringComparison` in fluentassertions? it's not exposed anywhere as an argument

**Comment by jnyrup** [comment]
There's no idiomatic way to pass a `StringComparison` to the string assertions.

There are ugly ways
```cs
"someString".Should().Match(e => string.Equals(e, "SoMeStRiNg", StringComparison.OrdinalIgnoreCase));
"someString".As<object>().Should().Be("SoMeStRiNg", StringComparer.OrdinalIgnoreCase);
```

Note that in v6 the `Equivalent` APIs besides casing also ignore leading and trailing whitespace.

For v7 we're currently having discussing on how to improve on this
https://github.com/fluentassertions/fluentassertions/issues/2339
https://github.com/fluentassertions/fluentassertions/issues/2364
