### ISSUE TITLE
xunit: define codefixes for TypeAsserts

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions.analyzers#146]
The asserts defined in https://github.com/xunit/assert.xunit/blob/main/TypeAsserts.cs

- [x] IsAssignableFrom<T>(object? @object) #238
- [x] IsAssignableFrom(Type expectedType, object? @object) #238
- [x] IsNotAssignableFrom<T>(object? @object) #239
- [x] IsNotAssignableFrom(Type expectedType, object? @object) #239
- [x] IsType<T>(object? @object) #240
- [x] IsType(Type expectedType, object? @object) #240
- [x] IsNotType<T>(object? @object) #241
- [x] IsNotType(Type expectedType, object? @object) #241

**Comment by Meir017** [comment]
```cs
// Xunit
XunitAssert.IsType<string>("foo");
XunitAssert.IsType(typeof(string), "foo");

// FluentAssertions
"foo".Should().BeOfType<string>();
"foo".Should().BeOfType(typeof(string));

// Xunit
XunitAssert.IsNotType<string>("foo");
XunitAssert.IsNotType(typeof(string), "foo");

// FluentAssertions
"foo".Should().NotBeOfType<string>();
"foo".Should().NotBeOfType(typeof(string));


XunitAssert.IsAssignableFrom<string>("foo");
XunitAssert.IsAssignableFrom(typeof(string), "foo");

// FluentAssertions
"foo".Should().BeAssignableTo<string>();
"foo".Should().BeAssignableTo(typeof(string));
```
